import Head from "next/head";
import Image from "next/image";
import HomePage from "./home/Home";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Valiasr Programing department</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
